/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CustomError } from "../CustomError.ts";

/**
 * @description トークンの更新に成功
 */
export type PostAuthRefresh200 = {
  /**
   * @description 新しいアクセストークン
   * @type string
   */
  access_token: string;
  /**
   * @type string
   */
  token_type: string;
  /**
   * @description トークンの有効期限（秒）
   * @type integer
   */
  expires_in: number;
};

/**
 * @description リクエストが不正です
 */
export type PostAuthRefresh400 = CustomError;

/**
 * @description 無効なリフレッシュトークン
 */
export type PostAuthRefresh401 = CustomError;

/**
 * @description サーバー内部エラー
 */
export type PostAuthRefresh500 = CustomError;

export type PostAuthRefreshMutationRequest = {
  /**
   * @description リフレッシュトークン
   * @type string
   */
  refresh_token: string;
};

export type PostAuthRefreshMutationResponse = PostAuthRefresh200;

export type PostAuthRefreshMutation = {
  Response: PostAuthRefresh200;
  Request: PostAuthRefreshMutationRequest;
  Errors: PostAuthRefresh400 | PostAuthRefresh401 | PostAuthRefresh500;
};
