/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ToZod } from "@kubb/plugin-zod/utils";
import { z } from "zod";
import type {
  GetCategories200,
  GetCategories401,
  GetCategories500,
  GetCategoriesQueryResponse,
} from "../../types/categoriesController/GetCategories.ts";
import { categorySchema } from "../categorySchema.ts";
import { customErrorSchema } from "../customErrorSchema.ts";

/**
 * @description カテゴリリストの取得に成功
 */
export const getCategories200Schema = z.object({
  data: z.array(
    z.lazy(() => categorySchema).describe("カテゴリを表現するオブジェクト"),
  ),
}) as unknown as ToZod<GetCategories200>;

/**
 * @description 認証が必要です
 */
export const getCategories401Schema = z
  .lazy(() => customErrorSchema)
  .describe("エラー情報") as unknown as ToZod<GetCategories401>;

/**
 * @description サーバー内部エラー
 */
export const getCategories500Schema = z
  .lazy(() => customErrorSchema)
  .describe("エラー情報") as unknown as ToZod<GetCategories500>;

export const getCategoriesQueryResponseSchema = z.lazy(
  () => getCategories200Schema,
) as unknown as ToZod<GetCategoriesQueryResponse>;
