/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ToZod } from "@kubb/plugin-zod/utils";
import { z } from "zod";
import type {
  PostCategories201,
  PostCategories400,
  PostCategories401,
  PostCategories422,
  PostCategories500,
  PostCategoriesMutationRequest,
  PostCategoriesMutationResponse,
} from "../../types/categoriesController/PostCategories.ts";
import { categorySchema } from "../categorySchema.ts";
import { createCategoryRequestSchema } from "../createCategoryRequestSchema.ts";
import { customErrorSchema } from "../customErrorSchema.ts";

/**
 * @description カテゴリの作成に成功
 */
export const postCategories201Schema = z
  .lazy(() => categorySchema)
  .describe(
    "カテゴリを表現するオブジェクト",
  ) as unknown as ToZod<PostCategories201>;

/**
 * @description リクエストが不正です
 */
export const postCategories400Schema = z
  .lazy(() => customErrorSchema)
  .describe("エラー情報") as unknown as ToZod<PostCategories400>;

/**
 * @description 認証が必要です
 */
export const postCategories401Schema = z
  .lazy(() => customErrorSchema)
  .describe("エラー情報") as unknown as ToZod<PostCategories401>;

/**
 * @description バリデーションエラー
 */
export const postCategories422Schema = z
  .lazy(() => customErrorSchema)
  .describe("エラー情報") as unknown as ToZod<PostCategories422>;

/**
 * @description サーバー内部エラー
 */
export const postCategories500Schema = z
  .lazy(() => customErrorSchema)
  .describe("エラー情報") as unknown as ToZod<PostCategories500>;

export const postCategoriesMutationRequestSchema = z
  .lazy(() => createCategoryRequestSchema)
  .describe(
    "カテゴリ作成時のリクエストボディ",
  ) as unknown as ToZod<PostCategoriesMutationRequest>;

export const postCategoriesMutationResponseSchema = z.lazy(
  () => postCategories201Schema,
) as unknown as ToZod<PostCategoriesMutationResponse>;
