/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from "msw";
import { createGetCategoriesQueryResponse } from "../../mocks/categoriesController/createGetCategories.ts";
import type { GetCategoriesQueryResponse } from "../../types/categoriesController/GetCategories.ts";

export function getCategoriesHandler(
	data?:
		| GetCategoriesQueryResponse
		| ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Response),
) {
	return http.get("/categories", function handler(info) {
		if (typeof data === "function") return data(info);

		return new Response(
			JSON.stringify(data || createGetCategoriesQueryResponse(data)),
			{
				headers: {
					"Content-Type": "application/json",
				},
			},
		);
	});
}
