/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from "msw";
import { createPostCategoriesMutationResponse } from "../../mocks/categoriesController/createPostCategories.ts";
import type { PostCategoriesMutationResponse } from "../../types/categoriesController/PostCategories.ts";

export function postCategoriesHandler(
	data?:
		| PostCategoriesMutationResponse
		| ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Response),
) {
	return http.post("/categories", function handler(info) {
		if (typeof data === "function") return data(info);

		return new Response(
			JSON.stringify(data || createPostCategoriesMutationResponse(data)),
			{
				headers: {
					"Content-Type": "application/json",
				},
			},
		);
	});
}
