/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { createCustomError } from "./createCustomError.ts";

export function createInternalServerError() {
	return createCustomError();
}
