/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { createCustomError } from "./createCustomError";

export function createInternalServerError() {
  return createCustomError();
}
