/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from "@faker-js/faker";
import type { LoginRequest } from "../types/LoginRequest.ts";

/**
 * @description ログイン時のリクエストボディ
 */
export function createLoginRequest(data?: Partial<LoginRequest>): LoginRequest {
	return {
		...{
			email: faker.internet.email(),
			password: faker.string.alpha({ length: 8 }),
		},
		...(data || {}),
	};
}
