/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ToZod } from "@kubb/plugin-zod/utils";
import { z } from "zod";
import type {
  PostTodos201,
  PostTodos400,
  PostTodos401,
  PostTodos422,
  PostTodos500,
  PostTodosMutationRequest,
  PostTodosMutationResponse,
} from "../../types/todosController/PostTodos.ts";
import { createTodoRequestSchema } from "../createTodoRequestSchema.ts";
import { customErrorSchema } from "../customErrorSchema.ts";
import { todoSchema } from "../todoSchema.ts";

/**
 * @description Todo の作成に成功
 */
export const postTodos201Schema = z
  .lazy(() => todoSchema)
  .describe(
    "Todo アイテムを表現するオブジェクト",
  ) as unknown as ToZod<PostTodos201>;

/**
 * @description リクエストが不正です
 */
export const postTodos400Schema = z
  .lazy(() => customErrorSchema)
  .describe("エラー情報") as unknown as ToZod<PostTodos400>;

/**
 * @description 認証が必要です
 */
export const postTodos401Schema = z
  .lazy(() => customErrorSchema)
  .describe("エラー情報") as unknown as ToZod<PostTodos401>;

/**
 * @description バリデーションエラー
 */
export const postTodos422Schema = z
  .lazy(() => customErrorSchema)
  .describe("エラー情報") as unknown as ToZod<PostTodos422>;

/**
 * @description サーバー内部エラー
 */
export const postTodos500Schema = z
  .lazy(() => customErrorSchema)
  .describe("エラー情報") as unknown as ToZod<PostTodos500>;

export const postTodosMutationRequestSchema = z
  .lazy(() => createTodoRequestSchema)
  .describe(
    "Todo 作成時のリクエストボディ",
  ) as unknown as ToZod<PostTodosMutationRequest>;

export const postTodosMutationResponseSchema = z.lazy(
  () => postTodos201Schema,
) as unknown as ToZod<PostTodosMutationResponse>;
