/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ToZod } from "@kubb/plugin-zod/utils";
import { z } from "zod";
import type {
  PostAuthLogin200,
  PostAuthLogin400,
  PostAuthLogin401,
  PostAuthLogin500,
  PostAuthLoginMutationRequest,
  PostAuthLoginMutationResponse,
} from "../../types/authController/PostAuthLogin.ts";
import { authResponseSchema } from "../authResponseSchema.ts";
import { customErrorSchema } from "../customErrorSchema.ts";
import { loginRequestSchema } from "../loginRequestSchema.ts";

/**
 * @description ログインに成功
 */
export const postAuthLogin200Schema = z
  .lazy(() => authResponseSchema)
  .describe("認証成功時のレスポンス") as unknown as ToZod<PostAuthLogin200>;

/**
 * @description リクエストが不正です
 */
export const postAuthLogin400Schema = z
  .lazy(() => customErrorSchema)
  .describe("エラー情報") as unknown as ToZod<PostAuthLogin400>;

/**
 * @description 認証に失敗
 */
export const postAuthLogin401Schema = z
  .lazy(() => customErrorSchema)
  .describe("エラー情報") as unknown as ToZod<PostAuthLogin401>;

/**
 * @description サーバー内部エラー
 */
export const postAuthLogin500Schema = z
  .lazy(() => customErrorSchema)
  .describe("エラー情報") as unknown as ToZod<PostAuthLogin500>;

export const postAuthLoginMutationRequestSchema = z
  .lazy(() => loginRequestSchema)
  .describe(
    "ログイン時のリクエストボディ",
  ) as unknown as ToZod<PostAuthLoginMutationRequest>;

export const postAuthLoginMutationResponseSchema = z.lazy(
  () => postAuthLogin200Schema,
) as unknown as ToZod<PostAuthLoginMutationResponse>;
