import type { Metadata } from "next";
import type { ReactNode } from "react";
import "./globals.css";

type Props = {
  children: ReactNode;
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default ({ children }: Readonly<Props>): ReactNode => {
  return (
    <html lang="en">
      <body className="antialiased">{children}</body>
    </html>
  );
};
