/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from "msw";
import { createPostTodosMutationResponse } from "../../mocks/todosController/createPostTodos.ts";
import type { PostTodosMutationResponse } from "../../types/todosController/PostTodos.ts";

export function postTodosHandler(
	data?:
		| PostTodosMutationResponse
		| ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Response),
) {
	return http.post("/todos", function handler(info) {
		if (typeof data === "function") return data(info);

		return new Response(
			JSON.stringify(data || createPostTodosMutationResponse(data)),
			{
				headers: {
					"Content-Type": "application/json",
				},
			},
		);
	});
}
