/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from "msw";
import { createPutTodosTodoidMutationResponse } from "../../mocks/todosController/createPutTodosTodoid.ts";
import type { PutTodosTodoidMutationResponse } from "../../types/todosController/PutTodosTodoid.ts";

export function putTodosTodoidHandler(
	data?:
		| PutTodosTodoidMutationResponse
		| ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Response),
) {
	return http.put("/todos/:todoId", function handler(info) {
		if (typeof data === "function") return data(info);

		return new Response(
			JSON.stringify(data || createPutTodosTodoidMutationResponse(data)),
			{
				headers: {
					"Content-Type": "application/json",
				},
			},
		);
	});
}
