/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { postAuthLoginHandler } from "./authController/postAuthLoginHandler.ts";
import { postAuthRefreshHandler } from "./authController/postAuthRefreshHandler.ts";
import { getCategoriesHandler } from "./categoriesController/getCategoriesHandler.ts";
import { postCategoriesHandler } from "./categoriesController/postCategoriesHandler.ts";
import { deleteTodosTodoidHandler } from "./todosController/deleteTodosTodoidHandler.ts";
import { getTodosHandler } from "./todosController/getTodosHandler.ts";
import { getTodosTodoidHandler } from "./todosController/getTodosTodoidHandler.ts";
import { patchTodosTodoidToggleHandler } from "./todosController/patchTodosTodoidToggleHandler.ts";
import { postTodosHandler } from "./todosController/postTodosHandler.ts";
import { putTodosTodoidHandler } from "./todosController/putTodosTodoidHandler.ts";

export const handlers = [
	getTodosHandler(),
	postTodosHandler(),
	getTodosTodoidHandler(),
	putTodosTodoidHandler(),
	deleteTodosTodoidHandler(),
	patchTodosTodoidToggleHandler(),
	getCategoriesHandler(),
	postCategoriesHandler(),
	postAuthLoginHandler(),
	postAuthRefreshHandler(),
] as const;
