/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AuthResponse } from "../AuthResponse.ts";
import type { CustomError } from "../CustomError.ts";
import type { LoginRequest } from "../LoginRequest.ts";

/**
 * @description ログインに成功
 */
export type PostAuthLogin200 = AuthResponse;

/**
 * @description リクエストが不正です
 */
export type PostAuthLogin400 = CustomError;

/**
 * @description 認証に失敗
 */
export type PostAuthLogin401 = CustomError;

/**
 * @description サーバー内部エラー
 */
export type PostAuthLogin500 = CustomError;

export type PostAuthLoginMutationRequest = LoginRequest;

export type PostAuthLoginMutationResponse = PostAuthLogin200;

export type PostAuthLoginMutation = {
	Response: PostAuthLogin200;
	Request: PostAuthLoginMutationRequest;
	Errors: PostAuthLogin400 | PostAuthLogin401 | PostAuthLogin500;
};
