/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from "@faker-js/faker";
import type {
	PostAuthRefresh200,
	PostAuthRefreshMutationRequest,
	PostAuthRefreshMutationResponse,
} from "../../types/authController/PostAuthRefresh.ts";
import { createCustomError } from "../createCustomError.ts";

/**
 * @description トークンの更新に成功
 */
export function createPostAuthRefresh200(
	data?: Partial<PostAuthRefresh200>,
): PostAuthRefresh200 {
	return {
		...{
			access_token: faker.string.alpha(),
			token_type: faker.string.alpha(),
			expires_in: faker.number.int(),
		},
		...(data || {}),
	};
}

/**
 * @description リクエストが不正です
 */
export function createPostAuthRefresh400() {
	return createCustomError();
}

/**
 * @description 無効なリフレッシュトークン
 */
export function createPostAuthRefresh401() {
	return createCustomError();
}

/**
 * @description サーバー内部エラー
 */
export function createPostAuthRefresh500() {
	return createCustomError();
}

export function createPostAuthRefreshMutationRequest(
	data?: Partial<PostAuthRefreshMutationRequest>,
): PostAuthRefreshMutationRequest {
	return {
		...{ refresh_token: faker.string.alpha() },
		...(data || {}),
	};
}

export function createPostAuthRefreshMutationResponse(
	data?: Partial<PostAuthRefreshMutationResponse>,
): PostAuthRefreshMutationResponse {
	return data || faker.helpers.arrayElement<any>([createPostAuthRefresh200()]);
}
