/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from "@faker-js/faker";
import type { PostAuthLoginMutationResponse } from "../../types/authController/PostAuthLogin.ts";
import { createAuthResponse } from "../createAuthResponse.ts";
import { createCustomError } from "../createCustomError.ts";
import { createLoginRequest } from "../createLoginRequest.ts";

/**
 * @description ログインに成功
 */
export function createPostAuthLogin200() {
	return createAuthResponse();
}

/**
 * @description リクエストが不正です
 */
export function createPostAuthLogin400() {
	return createCustomError();
}

/**
 * @description 認証に失敗
 */
export function createPostAuthLogin401() {
	return createCustomError();
}

/**
 * @description サーバー内部エラー
 */
export function createPostAuthLogin500() {
	return createCustomError();
}

export function createPostAuthLoginMutationRequest() {
	return createLoginRequest();
}

export function createPostAuthLoginMutationResponse(
	data?: Partial<PostAuthLoginMutationResponse>,
): PostAuthLoginMutationResponse {
	return data || faker.helpers.arrayElement<any>([createPostAuthLogin200()]);
}
