/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch";
import client from "@kubb/plugin-client/clients/fetch";
import type {
  PostAuthRefresh400,
  PostAuthRefresh401,
  PostAuthRefresh500,
  PostAuthRefreshMutationRequest,
  PostAuthRefreshMutationResponse,
} from "../../types/authController/PostAuthRefresh.ts";
import {
  postAuthRefreshMutationRequestSchema,
  postAuthRefreshMutationResponseSchema,
} from "../../zod/authController/postAuthRefreshSchema.ts";

function getPostAuthRefreshUrl() {
  return `/auth/refresh` as const;
}

/**
 * @description リフレッシュトークンを使用してアクセストークンを更新します。
 * @summary トークンの更新
 * {@link /auth/refresh}
 */
export async function postAuthRefresh(
  data: PostAuthRefreshMutationRequest,
  config: Partial<RequestConfig<PostAuthRefreshMutationRequest>> & {
    client?: typeof client;
  } = {},
) {
  const { client: request = client, ...requestConfig } = config;

  const res = await request<
    PostAuthRefreshMutationResponse,
    ResponseErrorConfig<
      PostAuthRefresh400 | PostAuthRefresh401 | PostAuthRefresh500
    >,
    PostAuthRefreshMutationRequest
  >({
    method: "POST",
    url: getPostAuthRefreshUrl().toString(),
    data: postAuthRefreshMutationRequestSchema.parse(data),
    ...requestConfig,
  });
  return postAuthRefreshMutationResponseSchema.parse(res.data);
}
