/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ToZod } from "@kubb/plugin-zod/utils";
import { z } from "zod";
import type { InternalServerError } from "../types/InternalServerError.ts";
import { customErrorSchema } from "./customErrorSchema.ts";

export const internalServerErrorSchema = z
  .lazy(() => customErrorSchema)
  .describe("エラー情報") as unknown as ToZod<InternalServerError>;
