/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ToZod } from "@kubb/plugin-zod/utils";
import { z } from "zod";
import type { ValidationError } from "../types/ValidationError.ts";
import { customErrorSchema } from "./customErrorSchema.ts";

export const validationErrorSchema = z
  .lazy(() => customErrorSchema)
  .describe("エラー情報") as unknown as ToZod<ValidationError>;
