/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from "msw";
import { createPostAuthLoginMutationResponse } from "../../mocks/authController/createPostAuthLogin.ts";
import type { PostAuthLoginMutationResponse } from "../../types/authController/PostAuthLogin.ts";

export function postAuthLoginHandler(
	data?:
		| PostAuthLoginMutationResponse
		| ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Response),
) {
	return http.post("/auth/login", function handler(info) {
		if (typeof data === "function") return data(info);

		return new Response(
			JSON.stringify(data || createPostAuthLoginMutationResponse(data)),
			{
				headers: {
					"Content-Type": "application/json",
				},
			},
		);
	});
}
