/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ToZod } from "@kubb/plugin-zod/utils";
import { z } from "zod";
import type {
  GetTodosTodoid200,
  GetTodosTodoid401,
  GetTodosTodoid404,
  GetTodosTodoid500,
  GetTodosTodoidPathParams,
  GetTodosTodoidQueryResponse,
} from "../../types/todosController/GetTodosTodoid.ts";
import { customErrorSchema } from "../customErrorSchema.ts";
import { todoSchema } from "../todoSchema.ts";

export const getTodosTodoidPathParamsSchema = z.object({
  todoId: z.string().describe("Todo の一意識別子"),
}) as unknown as ToZod<GetTodosTodoidPathParams>;

/**
 * @description Todo の取得に成功
 */
export const getTodosTodoid200Schema = z
  .lazy(() => todoSchema)
  .describe(
    "Todo アイテムを表現するオブジェクト",
  ) as unknown as ToZod<GetTodosTodoid200>;

/**
 * @description 認証が必要です
 */
export const getTodosTodoid401Schema = z
  .lazy(() => customErrorSchema)
  .describe("エラー情報") as unknown as ToZod<GetTodosTodoid401>;

/**
 * @description リソースが見つかりません
 */
export const getTodosTodoid404Schema = z
  .lazy(() => customErrorSchema)
  .describe("エラー情報") as unknown as ToZod<GetTodosTodoid404>;

/**
 * @description サーバー内部エラー
 */
export const getTodosTodoid500Schema = z
  .lazy(() => customErrorSchema)
  .describe("エラー情報") as unknown as ToZod<GetTodosTodoid500>;

export const getTodosTodoidQueryResponseSchema = z.lazy(
  () => getTodosTodoid200Schema,
) as unknown as ToZod<GetTodosTodoidQueryResponse>;
