/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ToZod } from "@kubb/plugin-zod/utils";
import { z } from "zod";
import type {
  GetTodos200,
  GetTodos400,
  GetTodos401,
  GetTodos500,
  GetTodosQueryParams,
  GetTodosQueryResponse,
} from "../../types/todosController/GetTodos.ts";
import { customErrorSchema } from "../customErrorSchema.ts";
import { paginationSchema } from "../paginationSchema.ts";
import { todoSchema } from "../todoSchema.ts";

export const getTodosQueryParamsSchema = z.object({
  status: z
    .enum(["pending", "completed", "all"])
    .default("all")
    .describe("Todo の完了状態でフィルタリング"),
  category: z.string().describe("カテゴリ ID でフィルタリング").optional(),
  priority: z
    .enum(["low", "medium", "high"])
    .describe("優先度でフィルタリング")
    .optional(),
  search: z.string().describe("タイトルや説明での検索").optional(),
  page: z.coerce
    .number()
    .int()
    .min(1)
    .default(1)
    .describe("ページ番号（1から開始）"),
  limit: z.coerce
    .number()
    .int()
    .min(1)
    .max(100)
    .default(20)
    .describe("1ページあたりの件数"),
  sort: z
    .enum(["created_at", "updated_at", "due_date", "priority", "title"])
    .default("created_at")
    .describe("並び替えフィールド"),
  order: z.enum(["asc", "desc"]).default("desc").describe("並び替え順序"),
}) as unknown as ToZod<GetTodosQueryParams>;

/**
 * @description Todo リストの取得に成功
 */
export const getTodos200Schema = z.object({
  data: z.array(
    z.lazy(() => todoSchema).describe("Todo アイテムを表現するオブジェクト"),
  ),
  pagination: z.lazy(() => paginationSchema).describe("ページネーション情報"),
}) as unknown as ToZod<GetTodos200>;

/**
 * @description リクエストが不正です
 */
export const getTodos400Schema = z
  .lazy(() => customErrorSchema)
  .describe("エラー情報") as unknown as ToZod<GetTodos400>;

/**
 * @description 認証が必要です
 */
export const getTodos401Schema = z
  .lazy(() => customErrorSchema)
  .describe("エラー情報") as unknown as ToZod<GetTodos401>;

/**
 * @description サーバー内部エラー
 */
export const getTodos500Schema = z
  .lazy(() => customErrorSchema)
  .describe("エラー情報") as unknown as ToZod<GetTodos500>;

export const getTodosQueryResponseSchema = z.lazy(
  () => getTodos200Schema,
) as unknown as ToZod<GetTodosQueryResponse>;
