/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from "@faker-js/faker";
import type {
	PutTodosTodoidMutationResponse,
	PutTodosTodoidPathParams,
} from "../../types/todosController/PutTodosTodoid.ts";
import { createCustomError } from "../createCustomError.ts";
import { createTodo } from "../createTodo.ts";
import { createUpdateTodoRequest } from "../createUpdateTodoRequest.ts";

export function createPutTodosTodoidPathParams(
	data?: Partial<PutTodosTodoidPathParams>,
): PutTodosTodoidPathParams {
	return {
		...{ todoId: faker.string.alpha() },
		...(data || {}),
	};
}

/**
 * @description Todo の更新に成功
 */
export function createPutTodosTodoid200() {
	return createTodo();
}

/**
 * @description リクエストが不正です
 */
export function createPutTodosTodoid400() {
	return createCustomError();
}

/**
 * @description 認証が必要です
 */
export function createPutTodosTodoid401() {
	return createCustomError();
}

/**
 * @description リソースが見つかりません
 */
export function createPutTodosTodoid404() {
	return createCustomError();
}

/**
 * @description バリデーションエラー
 */
export function createPutTodosTodoid422() {
	return createCustomError();
}

/**
 * @description サーバー内部エラー
 */
export function createPutTodosTodoid500() {
	return createCustomError();
}

export function createPutTodosTodoidMutationRequest() {
	return createUpdateTodoRequest();
}

export function createPutTodosTodoidMutationResponse(
	data?: Partial<PutTodosTodoidMutationResponse>,
): PutTodosTodoidMutationResponse {
	return data || faker.helpers.arrayElement<any>([createPutTodosTodoid200()]);
}
