/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from "@faker-js/faker";
import type {
	DeleteTodosTodoidMutationResponse,
	DeleteTodosTodoidPathParams,
} from "../../types/todosController/DeleteTodosTodoid.ts";
import { createCustomError } from "../createCustomError.ts";

export function createDeleteTodosTodoidPathParams(
	data?: Partial<DeleteTodosTodoidPathParams>,
): DeleteTodosTodoidPathParams {
	return {
		...{ todoId: faker.string.alpha() },
		...(data || {}),
	};
}

/**
 * @description Todo の削除に成功
 */
export function createDeleteTodosTodoid204() {
	return undefined;
}

/**
 * @description 認証が必要です
 */
export function createDeleteTodosTodoid401() {
	return createCustomError();
}

/**
 * @description リソースが見つかりません
 */
export function createDeleteTodosTodoid404() {
	return createCustomError();
}

/**
 * @description サーバー内部エラー
 */
export function createDeleteTodosTodoid500() {
	return createCustomError();
}

export function createDeleteTodosTodoidMutationResponse(
	data?: Partial<DeleteTodosTodoidMutationResponse>,
): DeleteTodosTodoidMutationResponse {
	return (
		data || faker.helpers.arrayElement<any>([createDeleteTodosTodoid204()])
	);
}
